name: Test TCK endpoints

on:
    push:
    pull_request:

permissions:
    contents: read

jobs:
    tck-test:
        name: "Run TCK test"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v7.0.1

            - name: Prepare Hiero Solo
              id: solo
              uses: hiero-ledger/hiero-solo-action@v0.23.0
              with:
                  soloVersion: '0.87.1'
                  installMirrorNode: true

            - name: Run TCK test
              uses: manishdait/hiero-tck-runner@main
